# Generated by Django 5.2.14 on 2026-05-23 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Comida'), ('dinner', 'Cena'), ('snack', 'Snack')], max_length=12)),
                ('foods', models.JSONField(default=list)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein_g', models.PositiveIntegerField(default=0)),
                ('carbs_g', models.PositiveIntegerField(default=0)),
                ('fat_g', models.PositiveIntegerField(default=0)),
                ('eaten_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
