# Generated by Django 5.2.14 on 2026-05-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_supplement'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmeal',
            name='name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='savedmeal',
            name='note',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
