# Generated by Django 5.2.14 on 2026-05-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_activity_level_profile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='food_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
