# Generated by Django 5.2.14 on 2026-05-27 10:57

from django.db import migrations, models
from django.utils import timezone


def mark_existing_users_onboarded(apps, schema_editor):
    """Existing users with height + sex + DOB already filled have effectively
    done onboarding — don't shove them into the wizard on next visit."""
    Profile = apps.get_model("users", "Profile")
    now = timezone.now()
    Profile.objects.filter(
        height_cm__isnull=False,
        date_of_birth__isnull=False,
    ).exclude(sex="").update(onboarded_at=now)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_food_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_users_onboarded, migrations.RunPython.noop),
    ]
