# Generated by Django 5.2.14 on 2026-05-23 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetricsnapshot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('target_sessions', models.PositiveSmallIntegerField(blank=True, help_text='Number of finished sessions this month.', null=True)),
                ('target_volume_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Total kg lifted (weight × reps) over completed working sets.', max_digits=10, null=True)),
                ('target_bodyweight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'year', 'month'), name='unique_owner_month_goal'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='monthlygoal_month_range')],
            },
        ),
    ]
