# Generated by Django 5.2.14 on 2026-05-26 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_alter_usermetricsnapshot_owner_monthlygoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetricsnapshot',
            name='muscle_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='usermetricsnapshot',
            name='visceral_fat',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Tanita/Omron visceral-fat rating (~1–30).', max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='FatigueAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('muscle_slug', models.CharField(max_length=40)),
                ('delta', models.FloatField(help_text='Sets-equivalent units; can be negative.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'muscle_slug'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'date', 'muscle_slug'), name='fatigue_adjust_unique_owner_date_muscle')],
            },
        ),
        migrations.CreateModel(
            name='ReadinessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('sleep_quality', models.PositiveSmallIntegerField(help_text='1 (terrible) – 5 (great)')),
                ('stress_level', models.PositiveSmallIntegerField(help_text='1 (low) – 5 (high)')),
                ('soreness_overall', models.PositiveSmallIntegerField(help_text='1 (none) – 5 (very sore)')),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'date'), name='readiness_unique_owner_date'), models.CheckConstraint(condition=models.Q(('sleep_quality__gte', 1), ('sleep_quality__lte', 5), ('stress_level__gte', 1), ('stress_level__lte', 5), ('soreness_overall__gte', 1), ('soreness_overall__lte', 5)), name='readiness_1_to_5')],
            },
        ),
    ]
