# Generated by Django 5.2.14 on 2026-05-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_usermetricsnapshot_muscle_pct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlygoal',
            name='target_volume_kg',
        ),
    ]
