# Generated by Django 5.2.14 on 2026-05-23 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_alter_routine_owner_skippedday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('training_style', models.CharField(choices=[('bodybuilding', 'Bodybuilding'), ('powerlifting', 'Powerlifting'), ('powerbuilding', 'Powerbuilding')], max_length=20)),
                ('started_on', models.DateField(db_index=True)),
                ('length_weeks', models.PositiveSmallIntegerField(default=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_on'],
            },
        ),
    ]
