# Generated by Django 5.2.14 on 2026-06-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_add_abductors_adductors'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogramos'), ('lb', 'Libras')], default='', help_text='Blank = auto: lb for cable/machine, kg otherwise (feedback #8).', max_length=2),
        ),
    ]
