# Generated by Django 5.2.14 on 2026-06-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogramos'), ('lb', 'Libras')], default='', help_text='Blank = auto: lb for cable, kg otherwise. Per-exercise toggle (feedback #8).', max_length=2),
        ),
    ]
