# Generated by Django 5.2.14 on 2026-05-27 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_seed_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='p.ej. Lumbalgia, Impingement hombro derecho.', max_length=120)),
                ('body_region', models.CharField(choices=[('shoulder', 'Hombro'), ('elbow', 'Codo'), ('wrist', 'Muñeca'), ('neck', 'Cuello'), ('upper_back', 'Espalda alta'), ('lower_back', 'Espalda baja / lumbar'), ('hip', 'Cadera'), ('knee', 'Rodilla'), ('ankle', 'Tobillo'), ('chest', 'Pecho'), ('other', 'Otra')], default='other', max_length=20)),
                ('severity', models.CharField(choices=[('mild', 'Leve'), ('moderate', 'Moderada'), ('severe', 'Severa')], default='mild', max_length=10)),
                ('started_on', models.DateField(db_index=True)),
                ('resolved_on', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('avoid_exercises', models.ManyToManyField(blank=True, help_text='Ejercicios que NO se deben hacer mientras la lesión esté activa. La sesión y los pickers mostrarán una advertencia.', related_name='avoided_by_injuries', to='exercises.exercise')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_on', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('resolved_on__isnull', True), ('resolved_on__gte', models.F('started_on')), _connector='OR'), name='injury_resolved_after_started')],
            },
        ),
    ]
