# Generated by Django 5.2.14 on 2026-05-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilityExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('body_region', models.CharField(choices=[('shoulder', 'Hombro'), ('elbow', 'Codo'), ('wrist', 'Muñeca'), ('neck', 'Cuello'), ('upper_back', 'Espalda alta'), ('lower_back', 'Espalda baja / lumbar'), ('hip', 'Cadera'), ('knee', 'Rodilla'), ('ankle', 'Tobillo'), ('chest', 'Pecho'), ('other', 'Otra')], db_index=True, max_length=20)),
                ('instructions', models.TextField(help_text='Spanish instructions: sets/time, technique, what to feel.')),
                ('video_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['body_region', 'name'],
            },
        ),
    ]
