# Generated by Django 5.2.14 on 2026-05-27 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200)),
                ('page_area', models.CharField(blank=True, default='', help_text="Optional — which part of the app, in the reporter's words.", max_length=120)),
                ('description', models.TextField(max_length=2000)),
                ('page_url', models.CharField(blank=True, default='', help_text='URL the user was on when they clicked the bug button.', max_length=500)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('triaged', 'En revisión'), ('resolved', 'Resuelto')], db_index=True, default='open', max_length=10)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
